### ISSUE TITLE
Python error after upgrading to 3.9

### ISSUE THREAD

**Issue by fn-ix** [rndusr/stig#185]
Hi!

I'm getting the following error when running stig after upgrading Python to 3.9. Stig itself actually seems to work fine, it just outputs this to the console:

````
Traceback (most recent call last):
  File "/usr/bin/stig", line 33, in <module>
    sys.exit(load_entry_point('stig==0.10.1a0', 'console_scripts', 'stig')())
  File "/usr/lib/python3.9/site-packages/stig/__init__.py", line 24, in run
    main.run()
  File "/usr/lib/python3.9/site-packages/stig/main.py", line 192, in run
    tasks = tuple(task for task in asyncio.Task.all_tasks() if not task.done())
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
````

**Comment by rndusr** [comment]
This shouldn't be an issue with the current release.

Please upgrade and let me know if that fixes it.

**Comment by fn-ix** [comment]
Alright, I expected stig to be up-to-date in my distro's repos, which it isn't, so I'll wait until it gets updated, as it isn't a critical issue. Closing for now, sorry for the trouble.

**Comment by rndusr** [comment]
No worries.

If your distro has packaged it, you can install the latest release quite cleanly with pipx.
https://github.com/pipxproject/pipx
